name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
        DIRECTORY: ${{ secrets.DIRECTORY }}
      with:
         source: "."
         target: ${{ secrets.DIRECTORY }}
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        NAME: ${{ secrets.NAME }}
        DIRECTORY: ${{ secrets.DIRECTORY }}
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
        script: |
          nvm use 15.8.0
          yarn --cwd ${{ secrets.DIRECTORY }}
          pm2 restart ${{ secrets.NAME }}
